name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/20 * * * *"
permissions:
  contents: write
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "minjer.tsai@gmail.com"
          git config --local user.name "koushitw"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Make Program Every Day!"
          git push
